n1=int(input("enter first number"))
n2=int(input("enter second number"))
print("sum is:",n1+n2)
print("difference is:",n1-n2)
print("product is:",n1*n2)
print("division is:",n1/n2)
print("remainder is:",n1%n2)
print("floor division is:",n1//n2)
print("exponent is:",n1**n2)